version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3020:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/plex_market_data

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plex_market_data

volumes:
  postgres_data:

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    depends_on:
      - frontend